### ISSUE TITLE
Nomad Basics - run first job

### ISSUE THREAD

**Issue by rejackson73** [hashicorp/field-workshops-nomad#109]
Here is the link to the track:
https://play.instruqt.com/hashicorp/tracks/nomad-basics/challenges/run-first-job/assignment

the track has the participant run 'nomad status' with language below...
"The command returns a high level view of the status of the redis job, most importantly it's status, "running", and date submitted."

I didn't want to change directly as this may just be personal preference, but as 'nomad status' is fairly generic, I would change the text to the following:
"The command returns a high level view of any jobs running on the Nomad cluster, most importantly it's status, "running", and date submitted.  As we only have one job running (redis), that is the only one listed."

**Comment by rberlind** [comment]
I fixed this today, @rejackson73 while making all Nomad Instruqt tracks private.
