### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by phanclan** [hashicorp/field-workshops-nomad#53]
The following should line should be port 9002 not 9001
2. The `dashboard` task group runs a web dashboard  in a container running the `hashicorpnomad/counter-dashboard` Docker image on port 9001 on the bridge network.

**Comment by rberlind** [comment]
I'm fixing this while adding an Instructor guide for the Introduction to Nomad workshop

**Comment by lhaig** [comment]
Closing this out as @rberlind fixed this in the track.
