### ISSUE TITLE
Remove insensitive language

### ISSUE THREAD

**Issue by rberlind** [hashicorp/field-workshops-nomad#65]
This is aligned with HashiCorp's PDCT-002: Insensitive language PRD.

Remove "whitelist" from https://github.com/hashicorp/field-workshops-nomad/blob/master/docs/slides/multi-cloud/advanced-nomad/nomad-security.md and https://github.com/hashicorp/field-workshops-nomad/blob/master/instruqt-tracks/nomad-acls/track.yml

Consider changing name of default branch from "master" to "main", but wait until HashiCorp picks a standard.

**Comment by lhaig** [comment]
Reopening as the main branch request has not been implemented yet. @rberlind is there anything we need to do on the testing side to be able to change the main branch?

**Comment by rberlind** [comment]
Since the Remark slides are published to GitHub pages, we'll probably have to change the configuration for that to use main branch instead of master branch.  And we will also have to change "master" to "main" in  https://github.com/hashicorp/field-workshops-nomad/blob/master/.circleci/config.yml. Also, we need to change branch listed in https://app.circleci.com/pipelines/github/hashicorp/field-workshops-nomad.  References to slides should be ok since they use hashicorp.github.io/field-workshops-nomad without referring to branch.

**Comment by rberlind** [comment]
Completed
