### ISSUE TITLE
Correction for text in consul cluster build

### ISSUE THREAD

**Issue by malekai101** [hashicorp/field-workshops-nomad#73]
The text in the multi server lab for building a multi server cluster using consul (automatic-clustering-with-consul) says the following about client1 Nomad config file:  

> Now, look at the nomad-client1.hcl configuration file on the "Config Files" tab. This file indicates that the agent will run as a client node and connect to the nomad-server-1 server.

In the consul scenario, there is no reference to  _nomad-server-1_ in the config file.  The Nomad agent is using Consul to dynamically find the cluster.  I think this verbiage was copied from the previous challenge in which the server name is hard coded in the client config file.

**Comment by lhaig** [comment]
Closing this as it was fixed in the code. Thanks @malekai101
